version: '3'
services:
  httpd:
    #build: ./httpd
    image: httpd:2.4.41-alpine
    container_name: httpd
    volumes:
      - ./public_html/:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
